/*!
    @file TL_TestPoints.h
    @version 0.0.24.0

    \brief IO Client Test Points
    \project AUTOSAR, MQX Testpoints
    \author Petr Pomkla
    \author Freescale Semiconductor, Roznov pod Radhostem, Czech Republic

    \platform
    \peripheral
    \prerequisites
    \arversion 2.1.0
    \arrevision Rel.2.1, Rev.0017
    \swversion 2.1.0
    @lastmodusr B21889
    @lastmoddate Feb-22-2011

    Freescale Semiconductor Inc.
    (c) Copyright 2008 Freescale Semiconductor Inc.
    ALL RIGHTS RESERVED.
*/
/*! \addtogroup IOClient  @{ */

#ifndef IOCLIENT_TESTPOINTS_H
#define IOCLIENT_TESTPOINTS_H

/******************* type definitions ****************************************/

/*!
    \brief Supported remote function calls
*/
typedef enum {

    /**< PWM Test Points  */
    IOClient_TestPoint_Pwm_Channel_0 = 0,
    IOClient_TestPoint_Pwm_Channel_1,
    IOClient_TestPoint_Pwm_Channel_2,
    IOClient_TestPoint_Pwm_Channel_3,
    IOClient_TestPoint_Pwm_Channel_4,
    IOClient_TestPoint_Pwm_Channel_5,
    IOClient_TestPoint_Pwm_Channel_6,
    IOClient_TestPoint_Pwm_Channel_7,
    IOClient_TestPoint_Pwm_Channel_8,
    IOClient_TestPoint_Pwm_Channel_9,
    IOClient_TestPoint_Pwm_Channel_10,
    IOClient_TestPoint_Pwm_Channel_11,
    IOClient_TestPoint_Pwm_Channel_12,
    IOClient_TestPoint_Pwm_Channel_13,
    IOClient_TestPoint_Pwm_Channel_14,
    IOClient_TestPoint_Pwm_Channel_15,
    IOClient_TestPoint_Pwm_Channel_16,
    IOClient_TestPoint_Pwm_Channel_17,
    IOClient_TestPoint_Pwm_Channel_18,
    IOClient_TestPoint_Pwm_Channel_19,
    IOClient_TestPoint_Pwm_Channel_20,
    IOClient_TestPoint_Pwm_Channel_21,
    IOClient_TestPoint_Pwm_Channel_22,
    IOClient_TestPoint_Pwm_Channel_23,
    IOClient_TestPoint_Pwm_Channel_24,
    IOClient_TestPoint_Pwm_Channel_25,
    IOClient_TestPoint_Pwm_Channel_26,
    IOClient_TestPoint_Pwm_Channel_27,
    IOClient_TestPoint_Pwm_Channel_28,
    IOClient_TestPoint_Pwm_Channel_29,
    IOClient_TestPoint_Pwm_Channel_30,
    IOClient_TestPoint_Pwm_Channel_31,

    /**< ADC Test Points  */
    IOClient_TestPoint_Adc_Channel_0,
    IOClient_TestPoint_Adc_Channel_1,
    IOClient_TestPoint_Adc_Channel_2,
    IOClient_TestPoint_Adc_Channel_3,
    IOClient_TestPoint_Adc_Channel_4,
    IOClient_TestPoint_Adc_Channel_5,
    IOClient_TestPoint_Adc_Channel_6,
    IOClient_TestPoint_Adc_Channel_7,
    IOClient_TestPoint_Adc_Channel_8,
    IOClient_TestPoint_Adc_Channel_9,
    IOClient_TestPoint_Adc_Channel_10,
    IOClient_TestPoint_Adc_Channel_11,
    IOClient_TestPoint_Adc_Channel_12,
    IOClient_TestPoint_Adc_Channel_13,
    IOClient_TestPoint_Adc_Channel_14,
    IOClient_TestPoint_Adc_Channel_15,
    IOClient_TestPoint_Adc_Channel_16,
    IOClient_TestPoint_Adc_Channel_17,
    IOClient_TestPoint_Adc_Channel_18,
    IOClient_TestPoint_Adc_Channel_19,
    IOClient_TestPoint_Adc_Channel_20,
    IOClient_TestPoint_Adc_Channel_21,
    IOClient_TestPoint_Adc_Channel_22,
    IOClient_TestPoint_Adc_Channel_23,
    IOClient_TestPoint_Adc_Channel_24,
    IOClient_TestPoint_Adc_Channel_25,
    IOClient_TestPoint_Adc_Channel_26,
    IOClient_TestPoint_Adc_Channel_27,
    IOClient_TestPoint_Adc_Channel_28,
    IOClient_TestPoint_Adc_Channel_29,
    IOClient_TestPoint_Adc_Channel_30,
    IOClient_TestPoint_Adc_Channel_31,

    /**< Mcu test poin to IO channel mapping (NI PXI-6723 @ Slot3) */
    IOClient_TestPoint_Mcu_ExtClk_0,
    IOClient_TestPoint_Mcu_ExtClk_1,
    IOClient_TestPoint_Mcu_ExtClk_2,

    /**< Port Test Points  */
    IOClient_TestPoint_Port_A,
    IOClient_TestPoint_Port_B,
    IOClient_TestPoint_Port_C,
    IOClient_TestPoint_Port_D,
    IOClient_TestPoint_Port_E,
    IOClient_TestPoint_Port_F,
    IOClient_TestPoint_Port_G,
    IOClient_TestPoint_Port_H,
    IOClient_TestPoint_Port_I,
    IOClient_TestPoint_Port_J,
    IOClient_TestPoint_Port_K,
    IOClient_TestPoint_Port_L,
    IOClient_TestPoint_Port_M,
    IOClient_TestPoint_Port_N,
    IOClient_TestPoint_Port_O,
    IOClient_TestPoint_Port_P,
    IOClient_TestPoint_Port_Q,
    IOClient_TestPoint_Port_R,
    IOClient_TestPoint_Port_S,
    IOClient_TestPoint_Port_T,
    IOClient_TestPoint_Port_U,
    IOClient_TestPoint_Port_V,
    IOClient_TestPoint_Port_W,
    IOClient_TestPoint_Port_X,
    IOClient_TestPoint_Port_Y,
    IOClient_TestPoint_Port_Z,
    IOClient_TestPoint_Port_AD0L,
    IOClient_TestPoint_Port_AD0H,
    IOClient_TestPoint_Port_AD1L,
    IOClient_TestPoint_Port_AD1H,

    /**< AUTOSAR - PortPin A0..A15 Test Points  */
    IOClient_TestPoint_Port_A0,
    IOClient_TestPoint_Port_A1,
    IOClient_TestPoint_Port_A2,
    IOClient_TestPoint_Port_A3,
    IOClient_TestPoint_Port_A4,
    IOClient_TestPoint_Port_A5,
    IOClient_TestPoint_Port_A6,
    IOClient_TestPoint_Port_A7,
    IOClient_TestPoint_Port_A8,
    IOClient_TestPoint_Port_A9,
    IOClient_TestPoint_Port_A10,
    IOClient_TestPoint_Port_A11,
    IOClient_TestPoint_Port_A12,
    IOClient_TestPoint_Port_A13,
    IOClient_TestPoint_Port_A14,
    IOClient_TestPoint_Port_A15,
    /**< MQX - AUTOSAR PortPins + PortPin A16..A80 Test Points  */
    IOClient_TestPoint_Port_A16,
    IOClient_TestPoint_Port_A17,
    IOClient_TestPoint_Port_A18,
    IOClient_TestPoint_Port_A19,
    IOClient_TestPoint_Port_A20,
    IOClient_TestPoint_Port_A21,
    IOClient_TestPoint_Port_A22,
    IOClient_TestPoint_Port_A23,
    IOClient_TestPoint_Port_A24,
    IOClient_TestPoint_Port_A25,
    IOClient_TestPoint_Port_A26,
    IOClient_TestPoint_Port_A27,
    IOClient_TestPoint_Port_A28,
    IOClient_TestPoint_Port_A29,
    IOClient_TestPoint_Port_A30,
    IOClient_TestPoint_Port_A31,
    IOClient_TestPoint_Port_A32,
    IOClient_TestPoint_Port_A33,
    IOClient_TestPoint_Port_A34,
    IOClient_TestPoint_Port_A35,
    IOClient_TestPoint_Port_A36,
    IOClient_TestPoint_Port_A37,
    IOClient_TestPoint_Port_A38,
    IOClient_TestPoint_Port_A39,
    IOClient_TestPoint_Port_A40,
    IOClient_TestPoint_Port_A41,
    IOClient_TestPoint_Port_A42,
    IOClient_TestPoint_Port_A43,
    IOClient_TestPoint_Port_A44,
    IOClient_TestPoint_Port_A45,
    IOClient_TestPoint_Port_A46,
    IOClient_TestPoint_Port_A47,
    IOClient_TestPoint_Port_A48,
    IOClient_TestPoint_Port_A49,
    IOClient_TestPoint_Port_A50,
    IOClient_TestPoint_Port_A51,
    IOClient_TestPoint_Port_A52,
    IOClient_TestPoint_Port_A53,
    IOClient_TestPoint_Port_A54,
    IOClient_TestPoint_Port_A55,
    IOClient_TestPoint_Port_A56,
    IOClient_TestPoint_Port_A57,
    IOClient_TestPoint_Port_A58,
    IOClient_TestPoint_Port_A59,
    IOClient_TestPoint_Port_A60,
    IOClient_TestPoint_Port_A61,
    IOClient_TestPoint_Port_A62,
    IOClient_TestPoint_Port_A63,
    IOClient_TestPoint_Port_A64,
    IOClient_TestPoint_Port_A65,
    IOClient_TestPoint_Port_A66,
    IOClient_TestPoint_Port_A67,
    IOClient_TestPoint_Port_A68,
    IOClient_TestPoint_Port_A69,
    IOClient_TestPoint_Port_A70,
    IOClient_TestPoint_Port_A71,
    IOClient_TestPoint_Port_A72,
    IOClient_TestPoint_Port_A73,
    IOClient_TestPoint_Port_A74,
    IOClient_TestPoint_Port_A75,
    IOClient_TestPoint_Port_A76,
    IOClient_TestPoint_Port_A77,
    IOClient_TestPoint_Port_A78,
    IOClient_TestPoint_Port_A79,
    IOClient_TestPoint_Port_A80,

    /**< AUTOSAR - PortPin B0..B15 Test Points  */
    IOClient_TestPoint_Port_B0,
    IOClient_TestPoint_Port_B1,
    IOClient_TestPoint_Port_B2,
    IOClient_TestPoint_Port_B3,
    IOClient_TestPoint_Port_B4,
    IOClient_TestPoint_Port_B5,
    IOClient_TestPoint_Port_B6,
    IOClient_TestPoint_Port_B7,
    IOClient_TestPoint_Port_B8,
    IOClient_TestPoint_Port_B9,
    IOClient_TestPoint_Port_B10,
    IOClient_TestPoint_Port_B11,
    IOClient_TestPoint_Port_B12,
    IOClient_TestPoint_Port_B13,
    IOClient_TestPoint_Port_B14,
    /**< MQX - AUTOSAR PortPins + PortPin B15..B80 Test Points  */
    IOClient_TestPoint_Port_B15,
    IOClient_TestPoint_Port_B16,
    IOClient_TestPoint_Port_B17,
    IOClient_TestPoint_Port_B18,
    IOClient_TestPoint_Port_B19,
    IOClient_TestPoint_Port_B20,
    IOClient_TestPoint_Port_B21,
    IOClient_TestPoint_Port_B22,
    IOClient_TestPoint_Port_B23,
    IOClient_TestPoint_Port_B24,
    IOClient_TestPoint_Port_B25,
    IOClient_TestPoint_Port_B26,
    IOClient_TestPoint_Port_B27,
    IOClient_TestPoint_Port_B28,
    IOClient_TestPoint_Port_B29,
    IOClient_TestPoint_Port_B30,
    IOClient_TestPoint_Port_B31,
    IOClient_TestPoint_Port_B32,
    IOClient_TestPoint_Port_B33,
    IOClient_TestPoint_Port_B34,
    IOClient_TestPoint_Port_B35,
    IOClient_TestPoint_Port_B36,
    IOClient_TestPoint_Port_B37,
    IOClient_TestPoint_Port_B38,
    IOClient_TestPoint_Port_B39,
    IOClient_TestPoint_Port_B40,
    IOClient_TestPoint_Port_B41,
    IOClient_TestPoint_Port_B42,
    IOClient_TestPoint_Port_B43,
    IOClient_TestPoint_Port_B44,
    IOClient_TestPoint_Port_B45,
    IOClient_TestPoint_Port_B46,
    IOClient_TestPoint_Port_B47,
    IOClient_TestPoint_Port_B48,
    IOClient_TestPoint_Port_B49,
    IOClient_TestPoint_Port_B50,
    IOClient_TestPoint_Port_B51,
    IOClient_TestPoint_Port_B52,
    IOClient_TestPoint_Port_B53,
    IOClient_TestPoint_Port_B54,
    IOClient_TestPoint_Port_B55,
    IOClient_TestPoint_Port_B56,
    IOClient_TestPoint_Port_B57,
    IOClient_TestPoint_Port_B58,
    IOClient_TestPoint_Port_B59,
    IOClient_TestPoint_Port_B60,
    IOClient_TestPoint_Port_B61,
    IOClient_TestPoint_Port_B62,
    IOClient_TestPoint_Port_B63,
    IOClient_TestPoint_Port_B64,
    IOClient_TestPoint_Port_B65,
    IOClient_TestPoint_Port_B66,
    IOClient_TestPoint_Port_B67,
    IOClient_TestPoint_Port_B68,
    IOClient_TestPoint_Port_B69,
    IOClient_TestPoint_Port_B70,
    IOClient_TestPoint_Port_B71,
    IOClient_TestPoint_Port_B72,
    IOClient_TestPoint_Port_B73,
    IOClient_TestPoint_Port_B74,
    IOClient_TestPoint_Port_B75,
    IOClient_TestPoint_Port_B76,
    IOClient_TestPoint_Port_B77,
    IOClient_TestPoint_Port_B78,
    IOClient_TestPoint_Port_B79,
    IOClient_TestPoint_Port_B80,

    /**< PortPin C0..C15 Test Points  */
    IOClient_TestPoint_Port_C0,
    IOClient_TestPoint_Port_C1,
    IOClient_TestPoint_Port_C2,
    IOClient_TestPoint_Port_C3,
    IOClient_TestPoint_Port_C4,
    IOClient_TestPoint_Port_C5,
    IOClient_TestPoint_Port_C6,
    IOClient_TestPoint_Port_C7,
    IOClient_TestPoint_Port_C8,
    IOClient_TestPoint_Port_C9,
    IOClient_TestPoint_Port_C10,
    IOClient_TestPoint_Port_C11,
    IOClient_TestPoint_Port_C12,
    IOClient_TestPoint_Port_C13,
    IOClient_TestPoint_Port_C14,
    IOClient_TestPoint_Port_C15,

    /**< PortPin D0..D15 Test Points  */
    IOClient_TestPoint_Port_D0,
    IOClient_TestPoint_Port_D1,
    IOClient_TestPoint_Port_D2,
    IOClient_TestPoint_Port_D3,
    IOClient_TestPoint_Port_D4,
    IOClient_TestPoint_Port_D5,
    IOClient_TestPoint_Port_D6,
    IOClient_TestPoint_Port_D7,
    IOClient_TestPoint_Port_D8,
    IOClient_TestPoint_Port_D9,
    IOClient_TestPoint_Port_D10,
    IOClient_TestPoint_Port_D11,
    IOClient_TestPoint_Port_D12,
    IOClient_TestPoint_Port_D13,
    IOClient_TestPoint_Port_D14,
    IOClient_TestPoint_Port_D15,

    /**< PortPin E0..E15 Test Points  */
    IOClient_TestPoint_Port_E0,
    IOClient_TestPoint_Port_E1,
    IOClient_TestPoint_Port_E2,
    IOClient_TestPoint_Port_E3,
    IOClient_TestPoint_Port_E4,
    IOClient_TestPoint_Port_E5,
    IOClient_TestPoint_Port_E6,
    IOClient_TestPoint_Port_E7,
    IOClient_TestPoint_Port_E8,
    IOClient_TestPoint_Port_E9,
    IOClient_TestPoint_Port_E10,
    IOClient_TestPoint_Port_E11,
    IOClient_TestPoint_Port_E12,
    IOClient_TestPoint_Port_E13,
    IOClient_TestPoint_Port_E14,
    IOClient_TestPoint_Port_E15,

    /**< PortPin F0..F15 Test Points  */
    IOClient_TestPoint_Port_F0,
    IOClient_TestPoint_Port_F1,
    IOClient_TestPoint_Port_F2,
    IOClient_TestPoint_Port_F3,
    IOClient_TestPoint_Port_F4,
    IOClient_TestPoint_Port_F5,
    IOClient_TestPoint_Port_F6,
    IOClient_TestPoint_Port_F7,
    IOClient_TestPoint_Port_F8,
    IOClient_TestPoint_Port_F9,
    IOClient_TestPoint_Port_F10,
    IOClient_TestPoint_Port_F11,
    IOClient_TestPoint_Port_F12,
    IOClient_TestPoint_Port_F13,
    IOClient_TestPoint_Port_F14,
    IOClient_TestPoint_Port_F15,

    /**< PortPin G0..G15 Test Points  */
    IOClient_TestPoint_Port_G0,
    IOClient_TestPoint_Port_G1,
    IOClient_TestPoint_Port_G2,
    IOClient_TestPoint_Port_G3,
    IOClient_TestPoint_Port_G4,
    IOClient_TestPoint_Port_G5,
    IOClient_TestPoint_Port_G6,
    IOClient_TestPoint_Port_G7,
    IOClient_TestPoint_Port_G8,
    IOClient_TestPoint_Port_G9,
    IOClient_TestPoint_Port_G10,
    IOClient_TestPoint_Port_G11,
    IOClient_TestPoint_Port_G12,
    IOClient_TestPoint_Port_G13,
    IOClient_TestPoint_Port_G14,
    IOClient_TestPoint_Port_G15,

    /**< PortPin H0..H15 Test Points  */
    IOClient_TestPoint_Port_H0,
    IOClient_TestPoint_Port_H1,
    IOClient_TestPoint_Port_H2,
    IOClient_TestPoint_Port_H3,
    IOClient_TestPoint_Port_H4,
    IOClient_TestPoint_Port_H5,
    IOClient_TestPoint_Port_H6,
    IOClient_TestPoint_Port_H7,
    IOClient_TestPoint_Port_H8,
    IOClient_TestPoint_Port_H9,
    IOClient_TestPoint_Port_H10,
    IOClient_TestPoint_Port_H11,
    IOClient_TestPoint_Port_H12,
    IOClient_TestPoint_Port_H13,
    IOClient_TestPoint_Port_H14,
    IOClient_TestPoint_Port_H15,

    /**< PortPin I0..I15 Test Points  */
    IOClient_TestPoint_Port_I0,
    IOClient_TestPoint_Port_I1,
    IOClient_TestPoint_Port_I2,
    IOClient_TestPoint_Port_I3,
    IOClient_TestPoint_Port_I4,
    IOClient_TestPoint_Port_I5,
    IOClient_TestPoint_Port_I6,
    IOClient_TestPoint_Port_I7,
    IOClient_TestPoint_Port_I8,
    IOClient_TestPoint_Port_I9,
    IOClient_TestPoint_Port_I10,
    IOClient_TestPoint_Port_I11,
    IOClient_TestPoint_Port_I12,
    IOClient_TestPoint_Port_I13,
    IOClient_TestPoint_Port_I14,
    IOClient_TestPoint_Port_I15,

    /**< PortPin J0..J15 Test Points  */
    IOClient_TestPoint_Port_J0,
    IOClient_TestPoint_Port_J1,
    IOClient_TestPoint_Port_J2,
    IOClient_TestPoint_Port_J3,
    IOClient_TestPoint_Port_J4,
    IOClient_TestPoint_Port_J5,
    IOClient_TestPoint_Port_J6,
    IOClient_TestPoint_Port_J7,
    IOClient_TestPoint_Port_J8,
    IOClient_TestPoint_Port_J9,
    IOClient_TestPoint_Port_J10,
    IOClient_TestPoint_Port_J11,
    IOClient_TestPoint_Port_J12,
    IOClient_TestPoint_Port_J13,
    IOClient_TestPoint_Port_J14,
    IOClient_TestPoint_Port_J15,

    /**< PortPin K0..K15 Test Points  */
    IOClient_TestPoint_Port_K0,
    IOClient_TestPoint_Port_K1,
    IOClient_TestPoint_Port_K2,
    IOClient_TestPoint_Port_K3,
    IOClient_TestPoint_Port_K4,
    IOClient_TestPoint_Port_K5,
    IOClient_TestPoint_Port_K6,
    IOClient_TestPoint_Port_K7,
    IOClient_TestPoint_Port_K8,
    IOClient_TestPoint_Port_K9,
    IOClient_TestPoint_Port_K10,
    IOClient_TestPoint_Port_K11,
    IOClient_TestPoint_Port_K12,
    IOClient_TestPoint_Port_K13,
    IOClient_TestPoint_Port_K14,
    IOClient_TestPoint_Port_K15,

    /**< PortPin L0..L15 Test Points  */
    IOClient_TestPoint_Port_L0,
    IOClient_TestPoint_Port_L1,
    IOClient_TestPoint_Port_L2,
    IOClient_TestPoint_Port_L3,
    IOClient_TestPoint_Port_L4,
    IOClient_TestPoint_Port_L5,
    IOClient_TestPoint_Port_L6,
    IOClient_TestPoint_Port_L7,
    IOClient_TestPoint_Port_L8,
    IOClient_TestPoint_Port_L9,
    IOClient_TestPoint_Port_L10,
    IOClient_TestPoint_Port_L11,
    IOClient_TestPoint_Port_L12,
    IOClient_TestPoint_Port_L13,
    IOClient_TestPoint_Port_L14,
    IOClient_TestPoint_Port_L15,

    /**< PortPin M0..M15 Test Points  */
    IOClient_TestPoint_Port_M0,
    IOClient_TestPoint_Port_M1,
    IOClient_TestPoint_Port_M2,
    IOClient_TestPoint_Port_M3,
    IOClient_TestPoint_Port_M4,
    IOClient_TestPoint_Port_M5,
    IOClient_TestPoint_Port_M6,
    IOClient_TestPoint_Port_M7,
    IOClient_TestPoint_Port_M8,
    IOClient_TestPoint_Port_M9,
    IOClient_TestPoint_Port_M10,
    IOClient_TestPoint_Port_M11,
    IOClient_TestPoint_Port_M12,
    IOClient_TestPoint_Port_M13,
    IOClient_TestPoint_Port_M14,
    IOClient_TestPoint_Port_M15,

    /**< PortPin N0..N15 Test Points  */
    IOClient_TestPoint_Port_N0,
    IOClient_TestPoint_Port_N1,
    IOClient_TestPoint_Port_N2,
    IOClient_TestPoint_Port_N3,
    IOClient_TestPoint_Port_N4,
    IOClient_TestPoint_Port_N5,
    IOClient_TestPoint_Port_N6,
    IOClient_TestPoint_Port_N7,
    IOClient_TestPoint_Port_N8,
    IOClient_TestPoint_Port_N9,
    IOClient_TestPoint_Port_N10,
    IOClient_TestPoint_Port_N11,
    IOClient_TestPoint_Port_N12,
    IOClient_TestPoint_Port_N13,
    IOClient_TestPoint_Port_N14,
    IOClient_TestPoint_Port_N15,

    /**< PortPin O0..O15 Test Points  */
    IOClient_TestPoint_Port_O0,
    IOClient_TestPoint_Port_O1,
    IOClient_TestPoint_Port_O2,
    IOClient_TestPoint_Port_O3,
    IOClient_TestPoint_Port_O4,
    IOClient_TestPoint_Port_O5,
    IOClient_TestPoint_Port_O6,
    IOClient_TestPoint_Port_O7,
    IOClient_TestPoint_Port_O8,
    IOClient_TestPoint_Port_O9,
    IOClient_TestPoint_Port_O10,
    IOClient_TestPoint_Port_O11,
    IOClient_TestPoint_Port_O12,
    IOClient_TestPoint_Port_O13,
    IOClient_TestPoint_Port_O14,
    IOClient_TestPoint_Port_O15,

    /**< PortPin P0..P15 Test Points  */
    IOClient_TestPoint_Port_P0,
    IOClient_TestPoint_Port_P1,
    IOClient_TestPoint_Port_P2,
    IOClient_TestPoint_Port_P3,
    IOClient_TestPoint_Port_P4,
    IOClient_TestPoint_Port_P5,
    IOClient_TestPoint_Port_P6,
    IOClient_TestPoint_Port_P7,
    IOClient_TestPoint_Port_P8,
    IOClient_TestPoint_Port_P9,
    IOClient_TestPoint_Port_P10,
    IOClient_TestPoint_Port_P11,
    IOClient_TestPoint_Port_P12,
    IOClient_TestPoint_Port_P13,
    IOClient_TestPoint_Port_P14,
    IOClient_TestPoint_Port_P15,

    /**< PortPin Q0..Q15 Test Points  */
    IOClient_TestPoint_Port_Q0,
    IOClient_TestPoint_Port_Q1,
    IOClient_TestPoint_Port_Q2,
    IOClient_TestPoint_Port_Q3,
    IOClient_TestPoint_Port_Q4,
    IOClient_TestPoint_Port_Q5,
    IOClient_TestPoint_Port_Q6,
    IOClient_TestPoint_Port_Q7,
    IOClient_TestPoint_Port_Q8,
    IOClient_TestPoint_Port_Q9,
    IOClient_TestPoint_Port_Q10,
    IOClient_TestPoint_Port_Q11,
    IOClient_TestPoint_Port_Q12,
    IOClient_TestPoint_Port_Q13,
    IOClient_TestPoint_Port_Q14,
    IOClient_TestPoint_Port_Q15,

    /**< PortPin R0..R15 Test Points  */
    IOClient_TestPoint_Port_R0,
    IOClient_TestPoint_Port_R1,
    IOClient_TestPoint_Port_R2,
    IOClient_TestPoint_Port_R3,
    IOClient_TestPoint_Port_R4,
    IOClient_TestPoint_Port_R5,
    IOClient_TestPoint_Port_R6,
    IOClient_TestPoint_Port_R7,
    IOClient_TestPoint_Port_R8,
    IOClient_TestPoint_Port_R9,
    IOClient_TestPoint_Port_R10,
    IOClient_TestPoint_Port_R11,
    IOClient_TestPoint_Port_R12,
    IOClient_TestPoint_Port_R13,
    IOClient_TestPoint_Port_R14,
    IOClient_TestPoint_Port_R15,

    /**< PortPin S0..S15 Test Points  */
    IOClient_TestPoint_Port_S0,
    IOClient_TestPoint_Port_S1,
    IOClient_TestPoint_Port_S2,
    IOClient_TestPoint_Port_S3,
    IOClient_TestPoint_Port_S4,
    IOClient_TestPoint_Port_S5,
    IOClient_TestPoint_Port_S6,
    IOClient_TestPoint_Port_S7,
    IOClient_TestPoint_Port_S8,
    IOClient_TestPoint_Port_S9,
    IOClient_TestPoint_Port_S10,
    IOClient_TestPoint_Port_S11,
    IOClient_TestPoint_Port_S12,
    IOClient_TestPoint_Port_S13,
    IOClient_TestPoint_Port_S14,
    IOClient_TestPoint_Port_S15,

    /**< PortPin T0..T15 Test Points  */
    IOClient_TestPoint_Port_T0,
    IOClient_TestPoint_Port_T1,
    IOClient_TestPoint_Port_T2,
    IOClient_TestPoint_Port_T3,
    IOClient_TestPoint_Port_T4,
    IOClient_TestPoint_Port_T5,
    IOClient_TestPoint_Port_T6,
    IOClient_TestPoint_Port_T7,
    IOClient_TestPoint_Port_T8,
    IOClient_TestPoint_Port_T9,
    IOClient_TestPoint_Port_T10,
    IOClient_TestPoint_Port_T11,
    IOClient_TestPoint_Port_T12,
    IOClient_TestPoint_Port_T13,
    IOClient_TestPoint_Port_T14,
    IOClient_TestPoint_Port_T15,

    /**< PortPin U0..U15 Test Points  */
    IOClient_TestPoint_Port_U0,
    IOClient_TestPoint_Port_U1,
    IOClient_TestPoint_Port_U2,
    IOClient_TestPoint_Port_U3,
    IOClient_TestPoint_Port_U4,
    IOClient_TestPoint_Port_U5,
    IOClient_TestPoint_Port_U6,
    IOClient_TestPoint_Port_U7,
    IOClient_TestPoint_Port_U8,
    IOClient_TestPoint_Port_U9,
    IOClient_TestPoint_Port_U10,
    IOClient_TestPoint_Port_U11,
    IOClient_TestPoint_Port_U12,
    IOClient_TestPoint_Port_U13,
    IOClient_TestPoint_Port_U14,
    IOClient_TestPoint_Port_U15,

    /**< PortPin V0..V15 Test Points  */
    IOClient_TestPoint_Port_V0,
    IOClient_TestPoint_Port_V1,
    IOClient_TestPoint_Port_V2,
    IOClient_TestPoint_Port_V3,
    IOClient_TestPoint_Port_V4,
    IOClient_TestPoint_Port_V5,
    IOClient_TestPoint_Port_V6,
    IOClient_TestPoint_Port_V7,
    IOClient_TestPoint_Port_V8,
    IOClient_TestPoint_Port_V9,
    IOClient_TestPoint_Port_V10,
    IOClient_TestPoint_Port_V11,
    IOClient_TestPoint_Port_V12,
    IOClient_TestPoint_Port_V13,
    IOClient_TestPoint_Port_V14,
    IOClient_TestPoint_Port_V15,

    /**< PortPin W0..W15 Test Points  */
    IOClient_TestPoint_Port_W0,
    IOClient_TestPoint_Port_W1,
    IOClient_TestPoint_Port_W2,
    IOClient_TestPoint_Port_W3,
    IOClient_TestPoint_Port_W4,
    IOClient_TestPoint_Port_W5,
    IOClient_TestPoint_Port_W6,
    IOClient_TestPoint_Port_W7,
    IOClient_TestPoint_Port_W8,
    IOClient_TestPoint_Port_W9,
    IOClient_TestPoint_Port_W10,
    IOClient_TestPoint_Port_W11,
    IOClient_TestPoint_Port_W12,
    IOClient_TestPoint_Port_W13,
    IOClient_TestPoint_Port_W14,
    IOClient_TestPoint_Port_W15,

    /**< PortPin X0..X15 Test Points  */
    IOClient_TestPoint_Port_X0,
    IOClient_TestPoint_Port_X1,
    IOClient_TestPoint_Port_X2,
    IOClient_TestPoint_Port_X3,
    IOClient_TestPoint_Port_X4,
    IOClient_TestPoint_Port_X5,
    IOClient_TestPoint_Port_X6,
    IOClient_TestPoint_Port_X7,
    IOClient_TestPoint_Port_X8,
    IOClient_TestPoint_Port_X9,
    IOClient_TestPoint_Port_X10,
    IOClient_TestPoint_Port_X11,
    IOClient_TestPoint_Port_X12,
    IOClient_TestPoint_Port_X13,
    IOClient_TestPoint_Port_X14,
    IOClient_TestPoint_Port_X15,

    /**< PortPin Y0..Y15 Test Points  */
    IOClient_TestPoint_Port_Y0,
    IOClient_TestPoint_Port_Y1,
    IOClient_TestPoint_Port_Y2,
    IOClient_TestPoint_Port_Y3,
    IOClient_TestPoint_Port_Y4,
    IOClient_TestPoint_Port_Y5,
    IOClient_TestPoint_Port_Y6,
    IOClient_TestPoint_Port_Y7,
    IOClient_TestPoint_Port_Y8,
    IOClient_TestPoint_Port_Y9,
    IOClient_TestPoint_Port_Y10,
    IOClient_TestPoint_Port_Y11,
    IOClient_TestPoint_Port_Y12,
    IOClient_TestPoint_Port_Y13,
    IOClient_TestPoint_Port_Y14,
    IOClient_TestPoint_Port_Y15,

    /**< PortPin Z0..Z15 Test Points  */
    IOClient_TestPoint_Port_Z0,
    IOClient_TestPoint_Port_Z1,
    IOClient_TestPoint_Port_Z2,
    IOClient_TestPoint_Port_Z3,
    IOClient_TestPoint_Port_Z4,
    IOClient_TestPoint_Port_Z5,
    IOClient_TestPoint_Port_Z6,
    IOClient_TestPoint_Port_Z7,
    IOClient_TestPoint_Port_Z8,
    IOClient_TestPoint_Port_Z9,
    IOClient_TestPoint_Port_Z10,
    IOClient_TestPoint_Port_Z11,
    IOClient_TestPoint_Port_Z12,
    IOClient_TestPoint_Port_Z13,
    IOClient_TestPoint_Port_Z14,
    IOClient_TestPoint_Port_Z15,

        /**< PortPin AD0L0..AD0L7 Test Points  */
    IOClient_TestPoint_Port_AD0,
    IOClient_TestPoint_Port_AD1,
    IOClient_TestPoint_Port_AD2,
    IOClient_TestPoint_Port_AD3,
    IOClient_TestPoint_Port_AD4,
    IOClient_TestPoint_Port_AD5,
    IOClient_TestPoint_Port_AD6,
    IOClient_TestPoint_Port_AD7,

    /**< PortPin AD0H0..AD0H7 Test Points  */
    IOClient_TestPoint_Port_AD8,
    IOClient_TestPoint_Port_AD9,
    IOClient_TestPoint_Port_AD10,
    IOClient_TestPoint_Port_AD11,
    IOClient_TestPoint_Port_AD12,
    IOClient_TestPoint_Port_AD13,
    IOClient_TestPoint_Port_AD14,
    IOClient_TestPoint_Port_AD15,

    /**< PortPin AD1L0..AD1L7 Test Points  */
    IOClient_TestPoint_Port_AD16,
    IOClient_TestPoint_Port_AD17,
    IOClient_TestPoint_Port_AD18,
    IOClient_TestPoint_Port_AD19,
    IOClient_TestPoint_Port_AD20,
    IOClient_TestPoint_Port_AD21,
    IOClient_TestPoint_Port_AD22,
    IOClient_TestPoint_Port_AD23,

    /**< PortPin AD1H0..AD1H7 Test Points  */
    IOClient_TestPoint_Port_AD24,
    IOClient_TestPoint_Port_AD25,
    IOClient_TestPoint_Port_AD26,
    IOClient_TestPoint_Port_AD27,
    IOClient_TestPoint_Port_AD28,
    IOClient_TestPoint_Port_AD29,
    IOClient_TestPoint_Port_AD30,
    IOClient_TestPoint_Port_AD31,

    /**< DMB configuration Test Point  */
    IOClient_TestPoint_Dmb_Status,

    /**< DMB Can control configuration Test Point  */
    IOClient_TestPoint_Can0,
    IOClient_TestPoint_Can1,
    IOClient_TestPoint_Can2,
    IOClient_TestPoint_Can3,
    IOClient_TestPoint_Can4,
    IOClient_TestPoint_Can5,
    IOClient_TestPoint_Can6,
    IOClient_TestPoint_Can7,

    /**< DMB Lin control configuration Test Point  */
    IOClient_TestPoint_Lin0,
    IOClient_TestPoint_Lin1,
    IOClient_TestPoint_Lin2,
    IOClient_TestPoint_Lin3,
    IOClient_TestPoint_Lin4,
    IOClient_TestPoint_Lin5,
    IOClient_TestPoint_Lin6,
    IOClient_TestPoint_Lin7,

    /**< DMB FlexRay control configuration Test Point  */
    IOClient_TestPoint_Fr1A,
    IOClient_TestPoint_Fr2A,
    IOClient_TestPoint_Fr1B,
    IOClient_TestPoint_Fr2B,

    /* Test point for CAN module (NI PXI 8464) */
    IOClient_TestPoint_CAN_CAN0,
    IOClient_TestPoint_CAN_CAN1,
    IOClient_TestPoint_CAN_CAN2,
    IOClient_TestPoint_CAN_CAN3,

    IOClient_TestPoint_CAN_LowCAN0,
    IOClient_TestPoint_CAN_LowCAN1,
    IOClient_TestPoint_CAN_LowCAN2,
    IOClient_TestPoint_CAN_LowCAN3,

    /* Test point for Multi-bank relay multiplexer (NI PXI-2576 @ slot 8)  */
    IOClient_TestPoint_Mux_4x1,
    IOClient_TestPoint_Mux_Ind,
    /* Channels */
    IOClient_TestPoint_Mux_Channel0,
    IOClient_TestPoint_Mux_Channel1,
    IOClient_TestPoint_Mux_Channel2,
    IOClient_TestPoint_Mux_Channel3,
    IOClient_TestPoint_Mux_Channel4,
    IOClient_TestPoint_Mux_Channel5,
    IOClient_TestPoint_Mux_Channel6,
    IOClient_TestPoint_Mux_Channel7,
    IOClient_TestPoint_Mux_Channel8,
    IOClient_TestPoint_Mux_Channel9,
    IOClient_TestPoint_Mux_Channel10,
    IOClient_TestPoint_Mux_Channel11,
    IOClient_TestPoint_Mux_Channel12,
    IOClient_TestPoint_Mux_Channel13,
    IOClient_TestPoint_Mux_Channel14,
    IOClient_TestPoint_Mux_Channel15,
    IOClient_TestPoint_Mux_Channel16,
    IOClient_TestPoint_Mux_Channel17,
    IOClient_TestPoint_Mux_Channel18,
    IOClient_TestPoint_Mux_Channel19,
    IOClient_TestPoint_Mux_Channel20,
    IOClient_TestPoint_Mux_Channel21,
    IOClient_TestPoint_Mux_Channel22,
    IOClient_TestPoint_Mux_Channel23,
    IOClient_TestPoint_Mux_Channel24,
    IOClient_TestPoint_Mux_Channel25,
    IOClient_TestPoint_Mux_Channel26,
    IOClient_TestPoint_Mux_Channel27,
    IOClient_TestPoint_Mux_Channel28,
    IOClient_TestPoint_Mux_Channel29,
    IOClient_TestPoint_Mux_Channel30,
    IOClient_TestPoint_Mux_Channel31,
    IOClient_TestPoint_Mux_Channel32,
    IOClient_TestPoint_Mux_Channel33,
    IOClient_TestPoint_Mux_Channel34,
    IOClient_TestPoint_Mux_Channel35,
    IOClient_TestPoint_Mux_Channel36,
    IOClient_TestPoint_Mux_Channel37,
    IOClient_TestPoint_Mux_Channel38,
    IOClient_TestPoint_Mux_Channel39,
    IOClient_TestPoint_Mux_Channel40,
    IOClient_TestPoint_Mux_Channel41,
    IOClient_TestPoint_Mux_Channel42,
    IOClient_TestPoint_Mux_Channel43,
    IOClient_TestPoint_Mux_Channel44,
    IOClient_TestPoint_Mux_Channel45,
    IOClient_TestPoint_Mux_Channel46,
    IOClient_TestPoint_Mux_Channel47,
    IOClient_TestPoint_Mux_Channel48,
    IOClient_TestPoint_Mux_Channel49,
    IOClient_TestPoint_Mux_Channel50,
    IOClient_TestPoint_Mux_Channel51,
    IOClient_TestPoint_Mux_Channel52,
    IOClient_TestPoint_Mux_Channel53,
    IOClient_TestPoint_Mux_Channel54,
    IOClient_TestPoint_Mux_Channel55,
    IOClient_TestPoint_Mux_Channel56,
    IOClient_TestPoint_Mux_Channel57,
    IOClient_TestPoint_Mux_Channel58,
    IOClient_TestPoint_Mux_Channel59,
    IOClient_TestPoint_Mux_Channel60,
    IOClient_TestPoint_Mux_Channel61,
    IOClient_TestPoint_Mux_Channel62,
    IOClient_TestPoint_Mux_Channel63,
    /* Common */
    IOClient_TestPoint_Mux_Common0,
    IOClient_TestPoint_Mux_Common1,
    IOClient_TestPoint_Mux_Common2,
    IOClient_TestPoint_Mux_Common3,
    IOClient_TestPoint_Mux_Common4,
    IOClient_TestPoint_Mux_Common5,
    IOClient_TestPoint_Mux_Common6,
    IOClient_TestPoint_Mux_Common7,
    IOClient_TestPoint_Mux_Common8,
    IOClient_TestPoint_Mux_Common9,
    IOClient_TestPoint_Mux_Common10,
    IOClient_TestPoint_Mux_Common11,
    IOClient_TestPoint_Mux_Common12,
    IOClient_TestPoint_Mux_Common13,
    IOClient_TestPoint_Mux_Common14,
    IOClient_TestPoint_Mux_Common15,

    /**< LIN Test Points  */
    IOClient_TestPoint_LIN_Channel_1,
    IOClient_TestPoint_LIN_Channel_2,
    IOClient_TestPoint_LIN_Channel_3,

    IOClient_TestPoint_HSDIO_Ch0,
    IOClient_TestPoint_HSDIO_Ch1,
    IOClient_TestPoint_HSDIO_Ch2,
    IOClient_TestPoint_HSDIO_Ch3,
    IOClient_TestPoint_HSDIO_Ch4,
    IOClient_TestPoint_HSDIO_Ch5,
    IOClient_TestPoint_HSDIO_Ch6,
    IOClient_TestPoint_HSDIO_Ch7,
    IOClient_TestPoint_HSDIO_Ch8,
    IOClient_TestPoint_HSDIO_Ch9,
    IOClient_TestPoint_HSDIO_Ch10,
    IOClient_TestPoint_HSDIO_Ch11,
    IOClient_TestPoint_HSDIO_Ch12,
    IOClient_TestPoint_HSDIO_Ch13,
    IOClient_TestPoint_HSDIO_Ch14,
    IOClient_TestPoint_HSDIO_Ch15,
    IOClient_TestPoint_HSDIO_Ch16,
    IOClient_TestPoint_HSDIO_Ch17,
    IOClient_TestPoint_HSDIO_Ch18,
    IOClient_TestPoint_HSDIO_Ch19,
    IOClient_TestPoint_HSDIO_Ch20,
    IOClient_TestPoint_HSDIO_Ch21,
    IOClient_TestPoint_HSDIO_Ch22,
    IOClient_TestPoint_HSDIO_Ch23,
    IOClient_TestPoint_HSDIO_Ch24,
    IOClient_TestPoint_HSDIO_Ch25,
    IOClient_TestPoint_HSDIO_Ch26,
    IOClient_TestPoint_HSDIO_Ch27,
    IOClient_TestPoint_HSDIO_Ch28,
    IOClient_TestPoint_HSDIO_Ch29,
    IOClient_TestPoint_HSDIO_Ch30,
    IOClient_TestPoint_HSDIO_Ch31,

    /**< PWR Test Points  */
    IOClient_TestPoint_Pwr_Channel_0,
    IOClient_TestPoint_Pwr_Channel_1,
    IOClient_TestPoint_Pwr_Channel_2,
    IOClient_TestPoint_Pwr_Debuger,
    IOClient_TestPoint_Pwr_EVB,

    /**< PWR Test Points  */
    IOClient_TestPoint_SciControl,
    IOClient_TestPoint_FPGA_Device0,

    /**< CLK Test Points  */
    IOClient_TestPoint_CLK_Card,

    IOClient_TestPoint_CLK_Ctr0,
    IOClient_TestPoint_CLK_Ctr1,
    IOClient_TestPoint_CLK_Ctr2,
    IOClient_TestPoint_CLK_Ctr3,
    IOClient_TestPoint_CLK_Ctr4,
    IOClient_TestPoint_CLK_Ctr5,
    IOClient_TestPoint_CLK_Ctr6,
    IOClient_TestPoint_CLK_Ctr7,

    IOClient_TestPoint_CLK_Trig0,
    IOClient_TestPoint_CLK_Trig1,
    IOClient_TestPoint_CLK_Trig2,
    IOClient_TestPoint_CLK_Trig3,
    IOClient_TestPoint_CLK_Trig4,
    IOClient_TestPoint_CLK_Trig5,
    IOClient_TestPoint_CLK_Trig6,
    IOClient_TestPoint_CLK_Trig7,
    IOClient_TestPoint_CLK_Trig8,
    IOClient_TestPoint_CLK_Trig9,
    IOClient_TestPoint_CLK_Trig10,
    IOClient_TestPoint_CLK_Trig11,
    IOClient_TestPoint_CLK_Trig12,
    IOClient_TestPoint_CLK_Trig13,
    IOClient_TestPoint_CLK_Trig14,
    IOClient_TestPoint_CLK_Trig15,
    IOClient_TestPoint_CLK_Trig16,
    IOClient_TestPoint_CLK_Trig17,
    IOClient_TestPoint_CLK_Trig18,
    IOClient_TestPoint_CLK_Trig19,
    IOClient_TestPoint_CLK_Trig20,
    IOClient_TestPoint_CLK_Trig21,
    IOClient_TestPoint_CLK_Trig22,
    IOClient_TestPoint_CLK_Trig23,
    IOClient_TestPoint_CLK_Trig24,
    IOClient_TestPoint_CLK_Trig25,
    IOClient_TestPoint_CLK_Trig26,
    IOClient_TestPoint_CLK_Trig27,
    IOClient_TestPoint_CLK_Trig28,
    IOClient_TestPoint_CLK_Trig29,
    IOClient_TestPoint_CLK_Trig30,
    IOClient_TestPoint_CLK_Trig31,
    IOClient_TestPoint_CLK_Trig32,
    IOClient_TestPoint_CLK_Trig33,
    IOClient_TestPoint_CLK_Trig34,
    IOClient_TestPoint_CLK_Trig35,
    IOClient_TestPoint_CLK_Trig36,
    IOClient_TestPoint_CLK_Trig37,
    IOClient_TestPoint_CLK_Trig38,
    IOClient_TestPoint_CLK_Trig39,

    /**< ICU Test Points  */
    IOClient_TestPoint_Icu_Channel_0,
    IOClient_TestPoint_Icu_Channel_1,
    IOClient_TestPoint_Icu_Channel_2,
    IOClient_TestPoint_Icu_Channel_3,
    IOClient_TestPoint_Icu_Channel_4,
    IOClient_TestPoint_Icu_Channel_5,
    IOClient_TestPoint_Icu_Channel_6,
    IOClient_TestPoint_Icu_Channel_7,
    IOClient_TestPoint_Icu_Channel_8,
    IOClient_TestPoint_Icu_Channel_9,
    IOClient_TestPoint_Icu_Channel_10,
    IOClient_TestPoint_Icu_Channel_11,
    IOClient_TestPoint_Icu_Channel_12,
    IOClient_TestPoint_Icu_Channel_13,
    IOClient_TestPoint_Icu_Channel_14,
    IOClient_TestPoint_Icu_Channel_15,
    IOClient_TestPoint_Icu_Channel_16,
    IOClient_TestPoint_Icu_Channel_17,
    IOClient_TestPoint_Icu_Channel_18,
    IOClient_TestPoint_Icu_Channel_19,
    IOClient_TestPoint_Icu_Channel_20,
    IOClient_TestPoint_Icu_Channel_21,
    IOClient_TestPoint_Icu_Channel_22,
    IOClient_TestPoint_Icu_Channel_23,
    IOClient_TestPoint_Icu_Channel_24,
    IOClient_TestPoint_Icu_Channel_25,
    IOClient_TestPoint_Icu_Channel_26,
    IOClient_TestPoint_Icu_Channel_27,
    IOClient_TestPoint_Icu_Channel_28,
    IOClient_TestPoint_Icu_Channel_29,
    IOClient_TestPoint_Icu_Channel_30,
    IOClient_TestPoint_Icu_Channel_31,

    /**< Timer/Counter Testpoints  */
    IOClient_TestPoint_TC_Ch0,
    IOClient_TestPoint_TC_Ch1,
    IOClient_TestPoint_TC_Ch2,
    IOClient_TestPoint_TC_Ch3,
    IOClient_TestPoint_TC_Ch4,
    IOClient_TestPoint_TC_Ch5,
    IOClient_TestPoint_TC_Ch6,
    IOClient_TestPoint_TC_Ch7,

    IOClient_TestPoint_TC_Trig0,
    IOClient_TestPoint_TC_Trig1,
    IOClient_TestPoint_TC_Trig2,
    IOClient_TestPoint_TC_Trig3,
    IOClient_TestPoint_TC_Trig4,
    IOClient_TestPoint_TC_Trig5,
    IOClient_TestPoint_TC_Trig6,
    IOClient_TestPoint_TC_Trig7,

    /**< HSDIO Trigger Testpoints  */
    IOClient_TestPoint_HSDIO_Trig0,
    IOClient_TestPoint_HSDIO_Trig1,
    IOClient_TestPoint_HSDIO_Trig2,
    IOClient_TestPoint_HSDIO_Trig3,

    /**< Fr Testpoints  */
    IOClient_TestPoint_FR_FlexRay1,
    IOClient_TestPoint_FR_FlexRay2

} IOClientTestPointType;

#endif /* IOCLIENT_TESTPOINTS_H */
